[build]
publish = "public"
command = "./stackbit-build.sh"

  [build.environment]
  HUGO_VERSION = "0.68.3"
  
[[headers]]
for = "/*"

  [headers.values]
  Content-Security-Policy = "upgrade-insecure-requests"
  Strict-Transport-Security = "max-age=15768000"
  X-Xss-Protection = "1; mode=block"
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Feature-Policy = "camera 'none'; geolocation 'none'; microphone 'none'"

[[redirects]]
	from = "/*"
	to = "/404/"
	status = 404